version: '3.7'

networks:
    internal:
        external: false
        driver: bridge
        name: ${CONTAINER_PREFIX}-internal

x-defaults: &defaults
    tty: true
    restart: ${DOCKER_RESTART_POLICY}
    logging:
        driver: "json-file"
        options:
            max-file: "10"
            max-size: "10m"

volumes:
    logs:
        driver: local

services:
    php:
        <<: *defaults
        #image: ${IMAGE_PHP}
        build: './docker/php'
        container_name: ${CONTAINER_PREFIX}-php
        working_dir: /var/www
        user: ${DEV_UID}:${DEV_GID}
        networks:
            - internal
        environment:
            docker: "true"
            ENVIRONMENT: ${ENVIRONMENT}
        volumes:
            - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - .:/var/www
            - logs:/var/www/logs
    web:
        <<: *defaults
        image: ${IMAGE_NGINX}
        container_name: ${CONTAINER_PREFIX}-nginx
        ports:
            - ${APP_IP}:${APP_PORTS}
        networks:
            - internal
        depends_on:
            - php
        volumes:
            - ./docker/nginx/conf.d/${ENVIRONMENT}.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www
