on: [workflow_dispatch]
name: 🚀 Deploy with FTP
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.1 ]
        node: [ 19 ]
        experimental: [ false ]
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: 🔨 Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: 🔨 Build Project
        run: |
          npm install
          ls -la
          pwd
          chmod -R 755 /public
          npm run build-prod

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
